export const SliderData = [
  {
    id: 1,
    type: 'dog',
    location: 'Belgrade',
    name: 'Bela',
    sex: 'male',
    size: 'small',
    age: 'junior',
    breed: 'mix',
    image: 'https://placedog.net/800/640?id=52',
    description:
      'Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor',
    vaccines: 'no',
    health: 'great',
    habits: 'barking',
  },
  {
    id: 2,
    type: 'dog',
    location: 'Novi Sad',
    name: 'Lunja',
    sex: 'male',
    size: 'small',
    age: 'junior',
    breed: 'mix',
    image: 'https://placedog.net/800/640?id=78',
    description:
      'Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor',
    vaccines: 'no',
    health: 'great',
    habits: 'barking',
  },
  {
    id: 3,
    type: 'dog',
    location: 'Nis',
    name: 'Lili',
    sex: 'male',
    size: 'small',
    age: 'junior',
    breed: 'mix',
    image: 'https://placedog.net/800/640?id=98',
    description:
      'Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor',
    vaccines: 'yes',
    health: 'great',
    habits: 'barking',
  },
  {
    id: 4,
    type: 'dog',
    location: 'Belgrade',
    name: 'Badi',
    sex: 'female',
    size: 'big',
    age: 'senior',
    breed: 'mix',
    image: 'https://placedog.net/800/640?id=12',
    description:
      'Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor',
    vaccines: 'no',
    health: 'great',
    habits: 'barking',
  },
  {
    id: 5,
    type: 'dog',
    location: 'Subotica',
    name: 'Maks',
    sex: 'female',
    size: 'medium',
    age: 'junior',
    breed: 'mix',
    image: 'https://placedog.net/800/640?id=122',
    description:
      'Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor',
    vaccines: 'yes',
    health: 'great',
    habits: 'walking',
  },
  {
    id: 6,
    type: 'dog',
    location: 'Novi Sad',
    name: 'Maza',
    sex: 'male',
    size: 'small',
    age: 'senior',
    breed: 'mix',
    image: 'https://placedog.net/800/640?id=66',
    description:
      'Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor',
    vaccines: 'no',
    health: 'great',
    habits: 'barking',
  },
  {
    id: 7,
    type: 'dog',
    location: 'Kragujevac',
    name: 'Laki',
    sex: 'female',
    size: 'small',
    age: 'junior',
    breed: 'mix',
    image: 'https://placedog.net/800/640?id=87',
    description:
      'Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor',
    vaccines: 'no',
    health: 'great',
    habits: 'barking',
  },
  {
    id: 8,
    type: 'dog',
    location: 'Belgrade',
    name: 'Zuca',
    sex: 'male',
    size: 'medium',
    age: 'senior',
    breed: 'mix',
    image: 'https://placedog.net/800/640?id=48',
    description:
      'Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor',
    vaccines: 'yes',
    health: 'medium',
    habits: 'eating shoes',
  },
];
