export const SliderData = [
  {
    id: 1,
    name: "ozren",
    type: "dog",
    location: "Belgrade",
    sex: "male",
    size: "small",
    age: "junior",
    breed: "mix",
    image: "https://placedog.net/800/640?id=52",
    description:
      "Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor",
    vaccines: "no",
    health: "great",
    habits: "barking",
    goodFor: "kids",
    badFor: "cats",
  },
  {
    id: 2,
    name: "Zuca",
    type: "dog",
    location: "Novi Sad",
    sex: "male",
    size: "small",
    age: "junior",
    breed: "mix",
    image: "https://placedog.net/800/640?id=78",
    description:
      "Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor",
    vaccines: "no",
    health: "great",
    habits: "barking",
    goodFor: "kids",
    badFor: "cats",
  },
  {
    id: 3,
    name: "Miki",
    type: "dog",
    location: "Nis",
    sex: "male",
    size: "small",
    age: "junior",
    breed: "mix",
    image: "https://placedog.net/800/640?id=98",
    description:
      "Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor",
    vaccines: "yes",
    health: "great",
    habits: "barking",
    goodFor: "kids",
    badFor: "cats",
  },
  {
    id: 4,
    name: "Zoki",
    type: "dog",
    location: "Belgrade",
    sex: "female",
    size: "big",
    age: "senior",
    breed: "mix",
    image: "https://placedog.net/800/640?id=12",
    description:
      "Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor",
    vaccines: "no",
    health: "great",
    habits: "barking",
    goodFor: "kids",
    badFor: "cats",
  },
  {
    id: 5,
    name: "Zak",
    type: "dog",
    location: "Subotica",
    sex: "female",
    size: "medium",
    age: "junior",
    breed: "mix",
    image: "https://placedog.net/800/640?id=122",
    description:
      "Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor",
    vaccines: "yes",
    health: "great",
    habits: "walking",
    goodFor: "kids",
    badFor: "cats",
  },
  {
    id: 6,
    name: "Jaramaz",
    type: "dog",
    location: "Novi Sad",
    sex: "male",
    size: "small",
    age: "senior",
    breed: "mix",
    image: "https://placedog.net/800/640?id=66",
    description:
      "Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor",
    vaccines: "no",
    health: "great",
    habits: "barking",
    goodFor: "kids",
    badFor: "cats",
  },
  {
    id: 7,
    name: "Dragan",
    type: "dog",
    location: "Kragujevac",
    sex: "female",
    size: "small",
    age: "junior",
    breed: "mix",
    image: "https://placedog.net/800/640?id=87",
    description:
      "Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor",
    vaccines: "no",
    health: "great",
    habits: "barking",
    goodFor: "kids",
    badFor: "cats",
  },
  {
    id: 8,
    name: "Ben",
    type: "dog",
    location: "Belgrade",
    sex: "male",
    size: "medium",
    age: "senior",
    breed: "mix",
    image: "https://placedog.net/800/640?id=48",
    description:
      "Enim deleniti quaerat beatae officiis. Quia perspiciatis voluptas incidunt est iste illum commodi quis. Consectetur occaecati beatae dolor Lorem ipsum dolor sit amet, consec tetur adipiscing elit. Nam condimentum tempus diam, ultricies sollicitudin erat facilisis eget. Vestibulum rhoncus dui vel eros laoreet consectetur. Vivamus eget elementum ligula, vitae pharetra quam. Lorem ipsum dolor sit amet, consec tetur adipiscing elit. Nam condimentum tempus diam, ultricies sollicitudin erat facilisis eget. Vestibulum rhoncus dui vel eros laoreet consectetur. Vivamus eget elementum ligula, vitae pharetra quam. ",
    vaccines: "yes",
    health:
      "Sterilisan, posebne potrebe. Lorem ipsum dolor sit amet, consec tetur adipiscing elit. Nam condimentum tempus diam, ultricies sollicitudin erat facilisis eget.",
    habits: "eating shoes",
    goodFor: "kids",
    badFor: "cats",
  },
];

export default SliderData;
